Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,54 +3,62 @@ on:
   push:
     branches:
       - main
-    types:
-      - commit
+
 jobs:
   release:
-    name: release
+    name: Release
     runs-on: ubuntu-latest
     steps:
-    - uses: actions/checkout@v2
-      with:
-        fetch-depth: 0
-    - name: Check commit messages and trigger if conditions are met
-      run: |
-        # Check the commit message using Git commands
-        if git log --format=%B -n 1 $GITHUB_SHA | grep -i "UpdatePackage"; then
-          echo "Commit message matched. Triggering the rest of the workflow..."
-          exit 0
-        else
-          echo "Commit message did not match. Skipping the workflow..."
-          exit 78
-        fi
-    - name: Release
-      uses: cycjimmy/semantic-release-action@v2.1.3
-      with:
-        extra_plugins: |
-          @semantic-release/changelog
-          @semantic-release/git
-        branch: main
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    - name: Create upm branch
-      run: |
-        git branch -d upm &> /dev/null || echo upm branch not found
-        git subtree split -P "$PKG_ROOT" -b upm
-        git checkout upm
-        if [[ -d "Samples" ]]; then
-          git mv Samples Samples~
-          rm -f Samples.meta
-          git config --global user.name 'github-bot'
-          git config --global user.email 'github-bot@users.noreply.github.com'
-          git commit -am "fix: Samples => Samples~"
-        fi
-        git push -f -u origin upm
-      env:
-        PKG_ROOT: Assets/com.egads.toolkit
-    - name: Create upm git tag
-      if: steps.semantic.outputs.new_release_published == 'true'
-      run: |
-        git tag $TAG upm
-        git push origin --tags
-      env:
-        TAG: upm/v${{ steps.semantic.outputs.new_release_version }}
+      - name: Checkout code
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+
+      - name: Check commit messages and trigger if conditions are met
+        run: |
+          # Check the commit message using Git commands
+          if git log --format=%B -n 1 $GITHUB_SHA | grep -i "UpdatePackage"; then
+            echo "Commit message matched. Triggering the rest of the workflow..."
+            exit 0
+          else
+            echo "Commit message did not match. Skipping the workflow..."
+            exit 78
+          fi
+
+      - name: Release
+        uses: cycjimmy/semantic-release-action@v2.1.3
+        with:
+          extra_plugins: |
+            @semantic-release/changelog
+            @semantic-release/git
+          branch: main
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        
+      - name: Create upm branch
+        run: |
+          if [[ -d "$PKG_ROOT" ]]; then
+            git branch -d upm &> /dev/null || echo upm branch not found
+            git subtree split -P "$PKG_ROOT" -b upm
+            git checkout upm
+            if [[ -d "Samples" ]]; then
+              git mv Samples Samples~
+              rm -f Samples.meta
+              git config --global user.name 'github-bot'
+              git config --global user.email 'github-bot@users.noreply.github.com'
+              git commit -am "fix: Samples => Samples~"
+            fi
+            git push -f -u origin upm
+          else
+            echo "$PKG_ROOT directory not found. Skipping upm branch creation."
+          fi
+        env:
+          PKG_ROOT: Assets/com.egads.toolkit
+
+      - name: Create upm git tag
+        if: steps.release.outputs.new_release_published == 'true'
+        run: |
+          git tag $TAG upm
+          git push origin --tags
+        env:
+          TAG: upm/v${{ steps.release.outputs.new_release_version }}
